name: news_app
description: A Flutter news app for MIREA course
version: 1.0.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.0  
  flip_card: ^0.6.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  intl_utils: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/cards.json